# .streamlit/secrets.toml

#sheet_id = '18xm6gkqkNh5qqSoygno5sw20vnMmuAyp'
#sheet_name = ""
#public_gsheets_url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}'
public_gsheets_url = "https://docs.google.com/spreadsheets/d/18xm6gkqkNh5qqSoygno5sw20vnMmuAyp/gviz/tq?tqx=out:csv&sheet=return"

